### ISSUE TITLE
[Easy][Hacktoberfest] Improve test

### ISSUE THREAD

**Issue by TiagoDanin** [TiagoDanin/NodeJS-i18n#1]
Add more tests

[My other projects - #Hacktoberfest](https://github.com/search?q=label%3Ahacktoberfest+state%3Aopen+type%3Aissue+user%3ATiagoDanin&type=Issues)

**Comment by Isaaclipse** [comment]
Hi can you explain what the issue is for this repo and how I can contribute?

**Comment by TiagoDanin** [comment]
Some test are missing in https://github.com/TiagoDanin/NodeJS-i18n/blob/master/test/test.js

- Comment

```javascript
// #i18n my comment
var name = 'Tiago'
```

- Promises
- Set default lang
```javascript
new Resources({
    lang: 'lang'
})
```
- Etc...
